# Autogenerated wrapper script for CGAL_jll for any
export GGAL_config_cmake

using boost_jll
using GMP_jll
using MPFR_jll
JLLWrappers.@generate_wrapper_header("CGAL")
JLLWrappers.@declare_file_product(GGAL_config_cmake)
function __init__()
    JLLWrappers.@generate_init_header(boost_jll, GMP_jll, MPFR_jll)
    JLLWrappers.@init_file_product(
        GGAL_config_cmake,
        "lib/cmake/CGAL/CGALConfig.cmake",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
